services:

  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      - web

  backend:
    build: .
    container_name: backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - ./core:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - web
    ports:
      - "8000:8000"

volumes:
  static_volume:
  media_volume:

networks:
  web:
    external: true
