# Generated by Django 4.2.30 on 2026-05-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_seed_split_home_banners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='image',
            field=models.FileField(help_text='فرمت\u200cهای JPG، PNG، WEBP و GIF', upload_to='banners/home/', verbose_name='تصویر یا GIF'),
        ),
    ]
