"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY",default='django-insecure-vhvotq9y&(y6g(0u1a199yz7v^@ig3n%y!-#%z_oj=4q!%3^w!')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG",cast=bool,default=True)


ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast= lambda v: [item.strip() for item in v.split(',')] ,default="*")

# Django Sites Framework
SITE_ID = config("SITE_ID", cast=int, default=1)
SITE_DOMAIN = config("SITE_DOMAIN", default="arvinofficial.ir")
SITE_NAME = config("SITE_NAME", default="فروشگاه آروین")



# Application definition

INSTALLED_APPS = [
    'core.apps.CoreConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'compressor',
    'django_ckeditor_5',
    'website',
    'accounts',
    'dashboard',
    'shop',
    'cart.apps.CartConfig',
    'order',
    'payment',
    'review',
    'blog',
    'django_user_agents',
    'rest_framework',
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.sites.middleware.CurrentSiteMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
    'core.middleware.SiteLayoutCookieMiddleware',
    'core.middleware.NoCacheHtmlMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.contrib.sites.context_processors.site',
                'shop.context_processors.shop_categories',
                'cart.context_processors.cart_processor',
                'core.context_processors.device.device',
                'website.context_processors.site_branding',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config("PGDB_NAME", default="shop_arvin"),
        'USER': config("PGDB_USER", default="shop_arvin_user"),
        'PASSWORD': config("PGDB_PASSWORD", default="your_password"),
        'HOST': config("PGDB_HOST", default="postgres"),
        'PORT': config("PGDB_PORT", default="5432"),
    }
}
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "core.password_validation.ASCIIOnlyPasswordValidator",
    },
    {
        'NAME': 'core.password_validation.PersianUserAttributeSimilarityValidator',
    },
    {
        'NAME': 'core.password_validation.PersianMinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'core.password_validation.PersianCommonPasswordValidator',
    },
    {
        'NAME': 'core.password_validation.PersianNumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'fa'

TIME_ZONE = config("TIME_ZONE", default="Asia/Tehran")

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
MEDIA_URL = "/media/"

_static_root = config("STATIC_ROOT", default=str(BASE_DIR / "staticfiles"))
STATIC_ROOT = Path(_static_root)
if not STATIC_ROOT.is_absolute():
    STATIC_ROOT = BASE_DIR / STATIC_ROOT

_media_root = config("MEDIA_ROOT", default=str(BASE_DIR / "media"))
MEDIA_ROOT = Path(_media_root)
if not MEDIA_ROOT.is_absolute():
    MEDIA_ROOT = BASE_DIR / MEDIA_ROOT

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# django-compressor
COMPRESS_ENABLED = config("COMPRESS_ENABLED", cast=bool, default=False)
COMPRESS_OFFLINE = config("COMPRESS_OFFLINE", cast=bool, default=False)

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
)

COMPRESS_FILTERS = {
    "css": [
        "compressor.filters.css_default.CssAbsoluteFilter",
        "compressor.filters.cssmin.rCSSMinFilter",
    ],
    "js": [
        "compressor.filters.jsmin.rJSMinFilter",
    ],
}

# Needed if COMPRESS_OFFLINE=True — templates use variable {% extends %}
def compress_offline_context():
    shared = {"STATIC_URL": STATIC_URL}
    yield {
        **shared,
        "is_mobile_site": False,
        "is_desktop_site": True,
        "base_template": "base-desktop.html",
        "dashboard_admin_base_template": "dashboard/admin/base-desktop.html",
        "dashboard_customer_base_template": "dashboard/customer/base-desktop.html",
    }
    yield {
        **shared,
        "is_mobile_site": True,
        "is_desktop_site": False,
        "base_template": "base-mobile.html",
        "dashboard_admin_base_template": "dashboard/admin/base-mobile.html",
        "dashboard_customer_base_template": "dashboard/customer/base-mobile.html",
    }


COMPRESS_OFFLINE_CONTEXT = "core.settings.compress_offline_context"

if config("COMPRESS_GZIP_ENABLED", cast=bool, default=False):
    COMPRESS_STORAGE = "compressor.storage.GzipCompressorFileStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrPhoneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'EXCEPTION_HANDLER': 'core.drf_handlers.persian_exception_handler',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}
MERCHANT_ID = config("MERCHANT_ID")
KAVENEGAR_API_KEY = config("KAVENEGAR_API_KEY")

# config('KAVENEGAR_API_KEY', default='')
# نام الگو در پنل کاوه‌نگار (بخش Lookup) — باید دقیقاً یکی باشد
KAVENEGAR_TEMPLATE = config('KAVENEGAR_TEMPLATE', default='verify')
# %token = کد ۶ رقمی OTP · %token2 = مدت اعتبار (دقیقه) از OTPCode.VALIDITY_MINUTES



LOGOUT_REDIRECT_URL = "/"
LOGIN_REDIRECT_URL = "/"

# PWA
PWA_APP_NAME = "arvinofficial"
PWA_SHORT_NAME = "Arvin"
PWA_APP_DESCRIPTION = "arvinofficial.ir"
PWA_CACHE_VERSION = "v3"

customColorPalette = [
    {
        'color': 'hsl(4, 90%, 58%)',
        'label': 'Red'
    },
    {
        'color': 'hsl(340, 82%, 52%)',
        'label': 'Pink'
    },
    {
        'color': 'hsl(291, 64%, 42%)',
        'label': 'Purple'
    },
    {
        'color': 'hsl(262, 52%, 47%)',
        'label': 'Deep Purple'
    },
    {
        'color': 'hsl(231, 48%, 48%)',
        'label': 'Indigo'
    },
    {
        'color': 'hsl(207, 90%, 54%)',
        'label': 'Blue'
    },
]

# CKEditor 5 Configuration
CKEDITOR_5_USER_LANGUAGE = True
CKEDITOR_5_CUSTOM_CSS = 'css/ckeditor5-fa-rtl.css'

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],
        'height': 400,
        'width': '100%',
        'language': 'fa',
    },
    'extends': {
        'language': 'fa',
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
        'code','subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable',],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties' ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
            ]
        },
        'list': {
            'properties': {
                'styles': True,
                'startIndex': True,
                'reversed': True,
            },
        },
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}

CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default=[],
    cast=lambda v: v if isinstance(v, list) else [i.strip() for i in v.split(",") if i.strip()],
)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


SESSION_COOKIE_AGE = 60 * 60 * 10  # 10 hours
SESSION_SAVE_EVERY_REQUEST = True
