# Generated by Django 4.2.30 on 2026-05-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_phone_username_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='smssettings',
            name='sms_enabled',
            field=models.BooleanField(default=True, help_text='فعال: ثبت\u200cنام فقط پس از تأیید پیامک. غیرفعال: ثبت\u200cنام با موبایل بدون ارسال پیامک.', verbose_name='ارسال پیامک OTP فعال است'),
        ),
    ]
