# Generated by Django 4.2.30 on 2026-05-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options_alter_smssettings_sms_enabled'),
        ('accounts', '0006_superuser_email_username'),
    ]

    operations = [
    ]
