# Generated by Django 4.2.30 on 2026-07-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_reset_accounts_id_sequences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smssettings',
            name='sms_enabled',
            field=models.BooleanField(default=True, help_text='فعال: ثبت\u200cنام با موبایل فقط پس از تأیید پیامک. غیرفعال: ثبت\u200cنام فقط با ایمیل.', verbose_name='ارسال پیامک OTP فعال است'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'customer'), (2, 'admin'), (3, 'superuser'), (4, 'marketer'), (5, 'editor'), (6, 'support')], default=1),
        ),
    ]
