# Generated by Django 4.2.30 on 2026-08-07 18:09

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_otpcode_user_and_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='شناسه ورود مشتری (اختیاری)', max_length=11, null=True, unique=True, validators=[accounts.validators.validate_iranian_cellphone_number], verbose_name='شماره موبایل'),
        ),
    ]
