# Generated by Django 4.2.30 on 2026-09-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_add_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimagemodel',
            name='image_alt',
            field=models.CharField(blank=True, default='', help_text='اگر خالی باشد، alt تصویر اصلی یا عنوان محصول استفاده می\u200cشود.', max_length=200, verbose_name='متن alt تصویر'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image_alt',
            field=models.CharField(blank=True, default='', help_text='اگر خالی باشد، عنوان محصول استفاده می\u200cشود.', max_length=200, verbose_name='متن alt تصویر'),
        ),
    ]
