# Generated by Django 4.2.30 on 2026-05-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_numeric_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='freight_notes',
            field=models.TextField(blank=True, default='', verbose_name='توضیحات باربری'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_method',
            field=models.IntegerField(choices=[(1, 'ارسال به آدرس'), (2, 'ارسال با باربری')], default=1, verbose_name='روش ارسال'),
        ),
    ]
