# Generated by Django 4.2.30 on 2026-05-21 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_shipping_method_freight'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutPricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_enabled', models.BooleanField(default=True, help_text='غیرفعال: بخش هزینه ارسال در خلاصه سفارش نمایش داده نمی\u200cشود.', verbose_name='نمایش هزینه ارسال')),
                ('shipping_tehran_label', models.CharField(default='تهران و حومه', max_length=100, verbose_name='عنوان نرخ تهران')),
                ('shipping_tehran_amount', models.PositiveIntegerField(default=35000, verbose_name='هزینه ارسال تهران و حومه (تومان)')),
                ('shipping_province_label', models.CharField(default='شهرستان\u200cها', max_length=100, verbose_name='عنوان نرخ شهرستان')),
                ('shipping_province_amount', models.PositiveIntegerField(default=50000, verbose_name='هزینه ارسال شهرستان\u200cها (تومان)')),
                ('tax_enabled', models.BooleanField(default=True, help_text='غیرفعال: مالیات در خلاصه سفارش محاسبه و نمایش داده نمی\u200cشود.', verbose_name='نمایش و محاسبه مالیات')),
                ('tax_percent', models.PositiveSmallIntegerField(default=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد مالیات')),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات هزینه ارسال و مالیات',
                'verbose_name_plural': 'تنظیمات هزینه ارسال و مالیات',
            },
        ),
    ]
