# Generated by Django 4.2.30 on 2026-05-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_checkout_pricing_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه ارسال'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='tax_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مالیات'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='جمع قیمت اقلام قبل از تخفیف، ارسال و مالیات.', max_digits=10, verbose_name='جمع کالاها'),
        ),
    ]
