# Generated by Django 4.2.30 on 2026-09-06 18:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_seed_iran_provinces_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardToCardReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_name', models.CharField(max_length=150, verbose_name='نام حساب واریزکننده')),
                ('payer_card_last4', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'چهار رقم آخر کارت را وارد کنید.')], verbose_name='چهار رقم آخر کارت')),
                ('image', models.ImageField(upload_to='receipts/card-to-card/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='عکس رسید')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ واریزی')),
                ('transfer_datetime', models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت رسید')),
                ('tracking_ref', models.CharField(blank=True, default='', max_length=64, verbose_name='شماره پیگیری بانکی')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_receipt', to='order.ordermodel', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'رسید کارت به کارت',
                'verbose_name_plural': 'رسیدهای کارت به کارت',
            },
        ),
    ]
