# Generated by Django 4.2.30 on 2026-09-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_card_to_card_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtocardreceipt',
            name='payer_card_last4',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='چهار رقم آخر کارت'),
        ),
        migrations.AlterField(
            model_name='cardtocardreceipt',
            name='payer_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='نام حساب واریزکننده'),
        ),
    ]
