# Generated by Django 4.2.30 on 2026-09-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_alt',
            field=models.CharField(blank=True, default='', help_text='اگر خالی باشد، عنوان پست استفاده می\u200cشود.', max_length=200, verbose_name='متن alt تصویر'),
        ),
        migrations.AddField(
            model_name='postimagemodel',
            name='image_alt',
            field=models.CharField(blank=True, default='', help_text='اگر خالی باشد، alt تصویر شاخص یا عنوان پست استفاده می\u200cشود.', max_length=200, verbose_name='متن alt تصویر'),
        ),
    ]
